### ISSUE TITLE
Seems like malware

### ISSUE THREAD

**Issue by sydneydatascience** [constverum/Quantdom#7]
My Norton antivirus complained and removed this tool :-)

**Comment by constverum** [comment]
It would be awesome if you could provide a screenshot/some data of that complaint in order to understand exactly what seemed suspicious to Norton.

**Comment by constverum** [comment]
Thank you!
I sent the report about “False Positive Detection” (https://submit.symantec.com/false_positive/) to Symantec, hope it will fix this wrong antivirus behavior.

Basically, the problem is not that it is infected or it’s some malware. The problem is that the tool is not digitally signed, and this causes a false positive detection. You can read more about it here - https://www.symantec.com/security-center/writeup/2010-051308-1854-99

**Comment by constverum** [comment]
Seems Semantic already fixed the issue.

> Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products: ...
> Note: Whitelisting may take up to 24 hours to take effect via Live Update

@sydneydatascience could you please check the behavior of antivirus one more time after a day or two (when updates will be available)?

**Comment by ArjunWhabi** [comment]
Hi Im getting the following error too :

Traceback (most recent call last):
  File "d:\winpython\python-3.6.7.amd64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\winpython\python-3.6.7.amd64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\WinPython\python-3.6.7.amd64\Scripts\quantdom.exe\__main__.py", line 5, in <module>
  File "d:\winpython\python-3.6.7.amd64\lib\site-packages\quantdom\__init__.py", line 29, in <module>
    from .ui import *  # noqa
  File "d:\winpython\python-3.6.7.amd64\lib\site-packages\quantdom\ui.py", line 10, in <module>
    from .lib import (  # noqa
ModuleNotFoundError: No module named 'quantdom.lib'

Now, I changed the setup.py file and manifest.in file as per PR # 6  [https://github.com/constverum/Quantdom/pull/6]

But now how do i install ??
Sorry Im a newbie
